
import elements.Patio;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import elements.Drawable;
import elements.Platform;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Daniel Lesmes
 */
public class Window extends javax.swing.JFrame implements Drawable {

    private Patio patio;
    private Timer time;

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        time = new Timer(40, acciones);
    }

    public void setPatio(Patio patio) {
        this.patio = patio;
        patio.setdrawable(this);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        patio.draw(g, this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_Q) {
            System.exit(0);
        }

        if (evt.getKeyCode() == KeyEvent.VK_SPACE
                | evt.getKeyCode() == KeyEvent.VK_LEFT
                | evt.getKeyCode() == KeyEvent.VK_RIGHT)
            patio.handleKey(evt.getKeyCode());
        time.start();
        
    }//GEN-LAST:event_formKeyPressed
   private ActionListener acciones = new ActionListener() {
       Platform plataform= new Platform(100, 50, 600, 20); 
        @Override
        public void actionPerformed(ActionEvent e) {
            patio.getPlayer().update();
            if (patio.getPlayer().getBounds().intersects(plataform.getBounds())) {
            patio.getPlayer().land(plataform.getY());
        }
            redraw();
        }
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Window window = new Window();
        Patio patio = new Patio(window.getWidth(), window.getHeight());
        window.setPatio(patio);
        window.setVisible(true);
    }

    @Override
    public void redraw() {
       repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
